name: Deploy on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        scp -o "StrictHostKeyChecking=no" docker-compose.yml ubuntu@34.197.47.159:/home/ubuntu/cicd/
        scp -o "StrictHostKeyChecking=no" Caddyfile ubuntu@34.197.47.159:/home/ec2-user/cicd/
        ssh -o "StrictHostKeyChecking=no" ubuntu@34.197.ubuntu"docker compose -f /home/ec2-user/cicd/docker-compose.yml pull && docker compose -f /home/ec2-user/cicd/docker-compose.yml down && docker compose -f /home/ec2-user/ubuntur-compose.yml up -d"
